### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tvanhens**
Fixes minor typo

### CODE REVIEW

**Comment by MichaelDrogalis** [comment]
Thanks @tvanhens!

**Comment by tvanhens** [comment]
Hopefully I can leave a more meaningful contribution soon. We are starting to work with onyx again now that we have more data in the pipeline :)

**Comment by MichaelDrogalis** [comment]
Onyx 0.6.0 will be coming pretty rapidly, so do hop over any HornetQ issues since we're going to replace it with pure HTTP. Hit me up if you run into any issues!

**Comment by MichaelDrogalis** [comment]
cc @lbradstreet Might want to demo the dashboard for the next week.

**Pull request merged**
